# Generated by Django 3.2.16 on 2025-03-01 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogicum',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), verbose_name='Дата рождения'),
        ),
    ]
