# Generated by Django 3.2.16 on 2025-02-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catrgory',
            new_name='category',
        ),
    ]
